version: '3.7'

services:
  backend:
    build: ./doc_summarizer_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./doc-summarizer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
